{{ $mediawiki := .Values.mariadb }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $mediawiki.name }}
  labels:
    {{- include "mediawiki.labels" . | nindent 4 }}
type: Opaque
stringData:
  database: {{ $mediawiki.secrets.database }}
  user: {{ $mediawiki.secrets.user }}
  password: {{ $mediawiki.secrets.password }}