# Default values.

mediawiki:
  name: mediawiki
  replicaCount: 1
  minReplicas: 1
  maxReplicas: 2
  image:
    repository: mediawiki
    # repository: bitnami/apache-exporter
    # repository: gcr.io/independent-bay-299305/mediawiki 
    tag: v2
    pullPolicy: IfNotPresent
  ports:
  - name: http
    containerPort: 80
    protocol: TCP
  resources:
    limits:
      cpu: 160m
      memory: 500Mi
    requests:
      cpu: 160m
      memory: 500Mi
  volumes:
  - name: mediawiki-volume
    accessmodes:
    - ReadWriteOnce
    path: /var/www/html/images
    size: 10Gi
  hpa:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  
  service:
    type: LoadBalancer #ClusterIP
    ports:
    - targetPort: http
      name: http
      protocol: TCP
      port: 80


mariadb:
  name: mariadb
  replicaCount: 1
  minReplicas: 1
  maxReplicas: 2
  image:
    repository: mariadb
    tag: latest
    pullPolicy: IfNotPresent
  ports:
  - containerPort: 3306
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  volumes:
  - name: mariadb-volume
    accessmodes:
    - ReadWriteOnce
    path: /var/lib/mysql
    size: 10Gi
  env:
  - name: MYSQL_RANDOM_ROOT_PASSWORD
    value: 'yes'
  secrets:
    database: my_wiki
    user: wikiuser
    password: example
    random_root_password: 'yes'

  service:
    type: ClusterIP
    ports:
    - targetPort: 3306
      port: 3306

